version: "3"
services:
  postgres:
    restart: always
    image: "postgres"
    ports:
      - "6969:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "gizmo-db"
volumes:
    db-data:
    pgadmin-data: